[features]
resolution = true
skip-lint = false

[toolchain]
anchor_version = "0.32.1"

[programs.localnet]
arxcess = "sDNRRyCwQptaRZHATCha4nSJCFCwpcDWH2NvJCCAwFk"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[programs.devnet]
arxcess = "sDNRRyCwQptaRZHATCha4nSJCFCwpcDWH2NvJCCAwFk"

[scripts]
test = "anchor test"
